### DISCUSSION TITLE
GitHub Actions で issue を自動作成する

### DISCUSSION THREAD

**Discussion by mimorimomi** [mimorimomi/whoami#59] [Scraps]
平日仕事がある日は issue を立てて読んだ記事とか雑なメモとかを取ってるんだけど、手動で作成するのをそろそろやめたい

**Comment by mimorimomi** [comment]
https://docs.github.com/ja/actions/managing-issues-and-pull-requests/scheduling-issue-creation
まず見るべきは公式かな〜

**Comment by mimorimomi** [comment]
やりたいこと

- [x] タイトルは `YYYY-MM-DD` の形式
- [x] Labels に Diary, Assignees に自分を指定
- [ ] 本文は prev: {前日の issue のリンク}, next: {翌日の issue のリンク（翌日はこの時点では分からないので手動で編集している）}
- [x] 平日朝 9:55 くらいに作成

**Reply by mimorimomi** [reply]
前日の issue リンク入れたいところだけど、ひとつ前の issue が絶対だとは限らないからどうやって機械的に見出すのかが見えてない

**Reply by mimorimomi** [reply]
リンク対応するなら issue を絶対前日のやつがそれにするか（運用でカバー）
でも他の雑多な issue あるんだよね、意味合い違うけど Discussion に逃がすか

**Reply by mimorimomi** [reply]
> CLOSE_PREVIOUS を true に設定すると、ワークフローによりラベルが一致する最新の Issue がクローズされます。
https://docs.github.com/ja/actions/managing-issues-and-pull-requests/scheduling-issue-creation

この実装ならちゃんとラベル一致を見てくれているので問題なさそう

**Comment by mimorimomi** [comment]
参考になりそうな記事
- https://qiita.com/yum_fishing/items/fd62dead30f92e24cdae
- https://zenn.dev/kanoe/articles/10c3e783671ae5
- https://tech.pepabo.com/2021/03/03/ec-efficiency-with-github-actions/

**Reply by mimorimomi** [reply]
どの Actions を利用するか、みたいなの迷ったけど書くのに慣れたいから公式の方法で自前？でやってみようかな

**Comment by mimorimomi** [comment]
祝日だけ作成やめたいけど、方法あるかなあ
これはできればやりたいくらいの気持ち

**Reply by mimorimomi** [reply]
できそうかも！流石すぎる、、、
https://zenn.dev/catnose99/scraps/b79f064332581a

**Reply by mimorimomi** [reply]
これ必須にするとハードル上がりそうだから、とりあえず自動作成が動いた後対応する

**Reply by mimorimomi** [reply]
CircleCI や GitHub Actions の cron を祝日だけ停止させたい
https://d.potato4d.me/entry/20211102-circleci-cron-holiday/

**Reply by mimorimomi** [reply]
これやる前にローカルで確認できるようにするのやった方がいいな

**Comment by mimorimomi** [comment]
cron 構文完全理解した
https://crontab.guru/#55_9_*_*_1-5
10時始業で9:55に作成してほしいから、 `55 9 * * 1-5` かな

**Reply by mimorimomi** [reply]
19時に実行されたんですけど、、、
完全理解構文を体現していて我ながら草

**Reply by mimorimomi** [reply]
あ、タイムゾーン設定？

**Reply by mimorimomi** [reply]
タイムゾーン指定できないんだ
https://zenn.dev/blancpanda/articles/github-actions-cron-timezone-jst

**Reply by mimorimomi** [reply]
9時間引いてこれになった
`- cron: 55 0 * * 1-5`

**Comment by mimorimomi** [comment]
3割くらいしか理解していないし公式のコピペだけど取り急ぎ！
あとは動かないところを直していこう、徐々に理解していくでしょ多分
```yml
name: Create weekdays note
on:
  schedule:
    - cron: 55 9 * * 1-5
jobs:
  weekdays_note:
    name: Create weekdays note
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create weekdays note
        run: |
          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: $(date +%Y-%m-%d)
          ASSIGNEES: mimorimomi
          LABELS: Diary
          BODY: |
            prev:
            next:
          PINNED: false
          CLOSE_PREVIOUS: false
```

**Reply by mimorimomi** [reply]
詳細なログ見れるようになってるのかな、確認！

**Comment by mimorimomi** [comment]
デバッグ ログを有効にする
https://docs.github.com/ja/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging

**Reply by mimorimomi** [reply]
`ACTIONS_RUNNER_DEBUG` を `true` にする？

**Reply by mimorimomi** [reply]
[GitHub]Actionsの動作確認時は忘れずにACTIONS_RUNNER_DEBUGとACTIONS_STEP_DEBUGを設定しよう
https://dev.classmethod.jp/articles/set-secrets-before-actions-test/

あーなんか、書くというよりは設定か

**Reply by mimorimomi** [reply]
> 1. SettingsタブのSecretsを開きます。
> 2. 「Add a new secret」を選択します。
> 3. NameにACTIONS_RUNNER_DEBUG、Valueにtrueを入れ、「Add secret」をクリックします。
> 4. 「Add a new secret」を選択します。
> 5. NameにACTIONS_STEP_DEBUG、Valueにtrueを入れ、「Add secret」をクリックします。

**Reply by mimorimomi** [reply]
Secrets and variables の Actions かな
記事は全く悪くなくて、 GitHub のメニューの項目って結構最近変わったんだね

**Reply by mimorimomi** [reply]
> This repository has no secrets.

ってなんかかっこいい

**Reply by mimorimomi** [reply]
New repository secret 押して、Name に `ACTIONS_RUNNER_DEBUG` Secret に `true` 入れて Add secret した
`ACTIONS_STEP_DEBUG ` も同様

**Reply by mimorimomi** [reply]
リポジトリに秘密ができてしまったな

**Comment by mimorimomi** [comment]
急ぎじゃないからのんびりデバッグしているんだけど、本当はローカルで確認できると嬉しい

**Reply by mimorimomi** [reply]
act というのがよさそう
https://zenn.dev/yumemi_inc/articles/203779a4eba922

**Comment by mimorimomi** [comment]
コケとるやないの！
しかも19時に実行されてるっぽい、、、

**Reply by mimorimomi** [reply]
`Error: Process completed with exit code 1.` とのこと

**Reply by mimorimomi** [reply]
`GraphQL: Resource not accessible by integration (repository.defaultBranchRef)` こっちか？

**Reply by mimorimomi** [reply]
あ〜これか、token 発行してないかも
https://qiita.com/athlaliel/items/cfef41949f62638c13da

**Reply by mimorimomi** [reply]
コードが `GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}` だったから `GITHUB_TOKEN` で Actions secrets 追加しようとしたんだけど

> Failed to add secret. Secret names must not start with GITHUB_.

そうなんだ、、

**Reply by mimorimomi** [reply]
`PERSONAL_ACCESS_TOKEN` にした、コードも修正！

**Comment by mimorimomi** [comment]
現状
```yml
name: Create weekdays note
on:
  schedule:
    - cron: 55 0 * * 1-5
jobs:
  weekdays_note:
    name: Create weekdays note
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create weekdays note
        run: |
          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: $(date +%Y-%m-%d)
          ASSIGNEES: mimorimomi
          LABELS: Diary
          BODY: |
            prev:
            next:
          PINNED: false
          CLOSE_PREVIOUS: false
```
リポジトリが private なのでイケてない感じのログ

**Reply by mimorimomi** [reply]
このコメントを pin できないのかな

**Comment by mimorimomi** [comment]
9:55 を過ぎたはずだが、まだできていない！
やっぱ cron 理解できていないのかな、、、

**Comment by mimorimomi** [comment]
issue できたが、なんかタイトル惜しい！
あと 10:39 に作成されている、、
> $(date +%Y-%m-%d)

**Reply by mimorimomi** [reply]
> Labels に Diary, Assignees に自分を指定

これはオケ！

**Reply by mimorimomi** [reply]
美しい解決方法ではないけど、別に始業開始直前にできてほしい訳ではないから時間早めるか

**Reply by mimorimomi** [reply]
https://crontab.guru/#0_0_*_*_1-5
`- cron: 0 0 * * 1-5`
これで！日本時間でいうと9時ちょうどのはずだけど、、、

**Reply by mimorimomi** [reply]
これ以上時間巻き戻す？と日付の取得もずれたりするのかな、、
そこだけ日本時間準拠だったりする？

**Reply by mimorimomi** [reply]
普通に`$(date +%Y-%m-%d)` という文字列を出していただけなのか、、、

**Reply by mimorimomi** [reply]
https://qiita.com/itouuuuuuuuu/items/ebf0d4c306b54747374f
ここはタイムゾーン指定できるのか！

**Reply by mimorimomi** [reply]
こんな感じかなあ、見よう見まねだけど
```yml
steps:
  - name: Set current datetime as env variable
    env:
      TZ: Asia/Tokyo
    run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
  - name: Create weekdays note
  ...
```

title のところは `TITLE: ${{ env.CURRENT_DATETIME }}` にした

**Comment by mimorimomi** [comment]
日付もちゃんと入ったんだけど、9:00（`cron: 0 0 * * 1-5`）にしているはずなのに 10:09 に作成された、、、

**Reply by mimorimomi** [reply]
そんなに厳密にやってくれる訳ではないのかな〜
https://tars0x9752.com/posts/github-actions-schedule-delay
https://qiita.com/tommy_aka_jps/items/5f4fe384008ffc9fa794

**Reply by mimorimomi** [reply]
もっと時間早めるか

**Reply by mimorimomi** [reply]
https://docs.github.com/ja/actions/monitoring-and-troubleshooting-workflows/using-workflow-run-logs
ちゃんとログを見てみよう

**Reply by mimorimomi** [reply]
timestamp 見てみたら `Thu, 01 Feb 2024 01:09:48 GMT` だった、やっぱ10:09に実行されたのか

**Reply by mimorimomi** [reply]
早けりゃもうなんでもいいよになったので `cron: 0 22 * * 1-5` にした

**Reply by mimorimomi** [reply]
<img width="281" alt="「fix: 早ければ早いほどいいよもう」というコミットメッセージ" src="https://github.com/mimorimomi/iam/assets/41240321/aea40130-4773-46cc-96ff-404bf10a692d">

我ながらカスみたいなメッセージ残した

**Reply by mimorimomi** [reply]
7:16 に作成された、やるじゃん

**Comment by mimorimomi** [comment]
これで土日できないのと、月曜できるのを確認できたら第一段階は完了だな！

**Reply by mimorimomi** [reply]
第二段階は祝日対応と前後のリンク自動で挿入（できるのか調べてもいない状態）
あとはローカルでデバッグする方法を確立

**Reply by mimorimomi** [reply]
土曜に作成された & 月曜作成されなかった、、、

**Reply by mimorimomi** [reply]
たぶん時間を `cron: 0 22 * * 1-5` にしたから日付遡ってしまって火水木金土にずれてしまっている気がする

**Reply by mimorimomi** [reply]
`cron: 0 0 * * 1-5` に戻した、多少遅れるのはいいから1時間以内には実行されてほしいな

**Reply by mimorimomi** [reply]
`cron: 0 0 * * 1-5` にしたらやっぱり実行されるの10時過ぎになってしまう
うーん、時間をずらしたうえで日月火水木にするか、美しくないけど、、、

**Reply by mimorimomi** [reply]
会社の毎日平日に実行される Actions も cron この書き方だったけど、9時ちょい過ぎくらいに実行されてる
リポジトリによって結構適当なのかな、ずれる原因が知りたい

**Reply by mimorimomi** [reply]
いやまあ、無課金だから何も言えないか

**Reply by mimorimomi** [reply]
分を微妙な時間にしたらいい感じに動くのでは説が浮上したからやってみる

**Reply by mimorimomi** [reply]
`cron: 17 0 * * 1-5` にして 17分遅らせたらきっかり 10:27 （`cron: 0 0 * * 1-5` の17分遅れ）に実行されてあのさあ

**Reply by mimorimomi** [reply]
時間を早めると祝日の制御がめんどくさくなりそうだから、`cron: 0 0 * * 1-5` で頑張ってほしいんだよなあ
祝日が別軸で取得できるのであればまあ、って感じかな

**Reply by mimorimomi** [reply]
ええ、なんか今日は9:57に作成された！嬉しいけど腑に落ちない、、、

**Reply by mimorimomi** [reply]
これで一旦様子見かな

**Comment by mimorimomi** [comment]
あ〜〜実装前に祝日が来てしまう

**Comment by mimorimomi** [comment]
Runners いじったらいい感じになるとかある？
というかそもそも Runners について理解していない

**Reply by mimorimomi** [reply]
https://docs.github.com/ja/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
https://docs.github.com/ja/actions/using-github-hosted-runners/about-github-hosted-runners

**Reply by mimorimomi** [reply]
一旦あとで

**Comment by mimorimomi** [comment]
前後の issue のリンクを挿入する

**Reply by mimorimomi** [reply]
`CLOSE_PREVIOUS: false`
これ true にすれば前日のがクローズされるのか

**Reply by mimorimomi** [reply]
とりあえず `CLOSE_PREVIOUS: true` にして前回の issue はクローズされるようにした

**Reply by mimorimomi** [reply]
previous というのがあるのでひとつ前の issue はなんかいい感じに情報取って来れそうな気がしている
まずは前 issue のリンクを挿入するのを調べてみようかな

**Reply by mimorimomi** [reply]
https://dev.classmethod.jp/articles/i-tried-operations-around-issue-with-github-cli-20/

```yml
previous_issue_number=$(gh issue list \
  --label "$LABELS" \
  --json number \
  --jq '.[0].number')
```

なるほど、`gh issue list` してラベルも見て最初のやつ、で前回を判断しているのか

**Reply by mimorimomi** [reply]
まてよ、`$new_issue_url` があるからこれで前回のを edit すればリンクいい感じに入るのでは？

**Reply by mimorimomi** [reply]
GitHub Copilot って Actions のことめっちゃ明るいのでは、、！？

**Reply by mimorimomi** [reply]
出してもらった

> GitHub CLIを使用して前回のIssueのリンクを取得し、それをprev:の箇所に挿入することができます。以下にその手順を示します。
> 
> gh issue listコマンドを使用して最新のIssueのリストを取得します。このコマンドはIssueの一覧を返しますが、-L 1オプションを使用して最新の1つだけを取得します。
>
> awkコマンドを使用してIssueのURLを抽出します。gh issue listコマンドの出力はタブ区切りのテーブル形式で、URLは最後の列にあります。
>
> echoコマンドを使用してURLをprev:の後に挿入します。
>
> 以下に、これらの手順を組み合わせたコマンドを示します。
>
> ```yml
> - name: Create weekday note
>   run: |
>     PREV_ISSUE_URL=$(gh issue list -L 1 | awk '{print $NF}')
>     gh issue create --title "Weekday note for $(date +'%Y-%m-%d')" --body "prev: $PREV_ISSUE_URL\nnext:" --assignee ${{ github.actor }} --label "weekday-note"
>   env:
>     GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
> ```
>
> このコマンドは、新しいIssueを作成するときに前回のIssueのURLをprev:の後に挿入します。

**Reply by mimorimomi** [reply]
こんな感じかなあ（...は略）
```yml
    steps:
      ...
      - name: Get previous issue number
        run: |
          echo "PREV_ISSUE_URL=$(gh issue list -L 1 | awk '{print $NF}')" >> $GITHUB_ENV"
      - name: Create weekdays note
        ...
        env:
          ...
          BODY: |
            prev: ${{ env.PREV_ISSUE_URL }}
            next:
```

**Reply by mimorimomi** [reply]
name を変数みたいなノリでガンガン増やさない方が良かったりするのかな
Create weekdays note の中で全部やった方がいい、、？

**Reply by mimorimomi** [reply]
> GitHub Actionsのワークフローにおけるstepsの数には特に制限はありません。ただし、以下の点を考慮すると良いでしょう。
>
> 可読性と保守性: ステップが多すぎると、ワークフローの全体像を理解するのが難しくなります。また、各ステップが何を行っているのかを追跡するのも難しくなります。ステップは独立したタスクを表すべきで、それぞれが明確な目的を持つようにすると良いでしょう。
>
> エラーハンドリング: ステップが多いと、エラーが発生したときにどのステップで問題が発生したのかを特定するのが難しくなる可能性があります。各ステップが独立していて、その目的が明確であれば、エラーの原因を特定しやすくなります。
>
> 実行時間: ステップが多いと、ワークフローの実行時間が長くなる可能性があります。各ステップは新しい環境で実行され、そのセットアップとクリーンアップには時間がかかります。不必要なステップを減らすことで、ワークフローの実行時間を短縮できます。
>
> したがって、必要なステップだけを含め、それぞれが独立したタスクを表すようにすると良いでしょう。

悪くはなさそうだけど、似たものはまとめた方がいいのかな

**Reply by mimorimomi** [reply]
push していったん様子見！明日出力されるかな〜
人生長いしのんびりデバッグしてこ！（手元で確認できるようにすべきだとは思っている）

**Reply by mimorimomi** [reply]
これさー next を入れる時は前の PR を編集する感じだよね

**Reply by mimorimomi** [reply]
next のリンクが判明したあとにやる必要がありそう（なんもわかってないけど）

**Reply by mimorimomi** [reply]
```yml
      - name: Get previous issue number
        run: |
          echo "PREV_ISSUE_URL=$(gh issue list -L 1 | awk '{print $NF}')" >> $GITHUB_ENV"
```
いやまてよ、見返してて思ったけどこれラベルとか見てないから多分直近のやつになっちゃうな
既存に合わせてラベル見るようにした方が美しい気がする

**Reply by mimorimomi** [reply]
コケた、やっぱ理解しないまま適当に AI に投げるの良くない例だな
CLI 確認できる環境をまず作ろう

**Reply by mimorimomi** [reply]
`gh issue list -L 1 | awk '{print $NF}'` したら `2024-03-12T01:08:55Z` って返ってきた、なんか違う気がするぞ

**Reply by mimorimomi** [reply]
すでに書いている
```yml
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
```
から抜いて
```
gh issue list --label "$LABELS" --json number --jq '.[0].number'
```
したら欲しい issue の番号返ってきた、これがいいかも

**Reply by mimorimomi** [reply]
こんなもんかな、ただ同じ処理を2度行っているからまとめたい
変数って name を跨げるのかな
```yml
    steps:
      ...
      - name: Get previous issue number
        run: |
          echo "PREV_ISSUE_URL=$(gh issue list --label "$LABELS" --json number --jq '.[0].number')" >> $GITHUB_ENV"
      - name: Create weekdays note
        ...
        env:
            prev: #${{ env.PREV_ISSUE_URL }}
```

**Comment by mimorimomi** [comment]
見るべきはこれな気がしてきた
https://cli.github.com/manual/gh_issue_create

**Reply by mimorimomi** [reply]
https://cli.github.com/manual/gh_issue

**Reply by mimorimomi** [reply]
CLI 何も理解していない状態で公式コピペでスタートしたので、ようやく分かってきた

**Comment by mimorimomi** [comment]
現状
```yml
name: Create weekdays note
on:
  schedule:
    - cron: 0 0 * * 1-5
jobs:
  weekdays_note:
    name: Create weekdays note
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Set current datetime as env variable
        env:
          TZ: Asia/Tokyo
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Create weekdays note
        run: |
          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: ${{ env.CURRENT_DATETIME }}
          ASSIGNEES: mimorimomi
          LABELS: Diary
          BODY: |
            prev:
            next:
          PINNED: false
          CLOSE_PREVIOUS: true
```
